apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: "receipt-service"
  namespace: "default"
spec:
  selector:
    matchLabels:
      app: "receipt-service"
  mtls:
    mode: PERMISSIVE