package service_desk_token

# loads the public key in PEM format
service_desk_public_key :=  base64.decode("LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFzNzEvOGpmRlBaclJ1aU5UQTNObwp2ZmFjLzFzbTkrS0FEZmt2YmRBYTZELzdITkNOek5iVElva3lxOG12V1hHcGxhMDUvUkVxVUVyZmFndXBRRjA3CnphRHo2RW1QRXJydDYyQkFlNnVRVDllLzJpSjZ5WXgwMjEyREF4UjJGSDJSTGc4Q2hTM3kwQjZRa2k3YkpHUnIKT0ovazhTbklXWVgzY0JUWGZITjQ3MUYwLzhzT1hsU2Y4dWUrYkw4dmNpcThuWHc5MUlQYktOYTdqR2NDWkRRSwpMNWU3RlFTZno0N21xcE81dTJpVU96VjRSaDdQNm1MSVpTSmpOeG1rTDVjZE1OMjdPU3IzYVNrUG9GMHZUcEQ5CmZlR2NSV0F2RXlhQnBvWjR2NkFNR2ptNkNZdHA1WlpCNVhYRmJhRlpmRDBrME1SUzkxS0VaOVpRTkRGNDhFSmoKaHdJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==")
# service_desk_public_key := opa.runtime().env.SERVICE_DESK_PUBLIC_KEY_PEM

# verifies the token signature agains the public key of the service_desk
token_has_valid_signature(token) := io.jwt.verify_rs256(token, service_desk_public_key)
