apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: "receipt-service-policy"
  namespace: default
spec:
  selector:
    matchLabels:
      app: receipt-service
  action: ALLOW
  rules:
    - to:
        - operation:
            methods: ["GET"]
            paths: ["/receipts/health"]
    #    - from:
    #        - source:
    #            ipBlocks:  ["192.168.49.1"] # 10.97.53.100"] # 127.0.0.1"] # 192.168.49.1"]  # 192.168.58.1"] # ["192.167.42.3"] # ["192.168.58.1"]   # 10.244.0.1
    -  to: # 10.244.0.1
         - operation: # todo in zukunft from checkout-service s.u.
             methods: ["POST"]
             paths: ["/receipts/receipts"] # /receipts/receipts
#    - from:
#        - source: # todo geht se statt sa für service entry? # todo: checkout service starten & testen
#            principals: [ "cluster.local/ns/default/sa/checkout-service" ]
#      to:
#        - operation:
#            methods: [ "POST" ]
#            paths: [ "*/receipts" ]