##################################################################################################
# bonus-booklet-service
##################################################################################################
---
apiVersion: v1
kind: Service
metadata:
  name: bonus-booklet-service
  labels:
    app: bonus-booklet-service
    service: bonus-booklet-service
spec:
  ports:
    - port: 3000
      name: http
  selector:
    app: bonus-booklet-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bonus-booklet-service
  labels:
    account: bonus-booklet-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bonus-booklet-service
spec:
  selector:
    matchLabels:
      app: bonus-booklet-service
  replicas: 1
  template:
    metadata:
      labels:
        app: bonus-booklet-service
    spec:
      serviceAccountName: bonus-booklet-service
      containers:
        - name: bonus-booklet-service
          image: tabeaschuster/bonus-booklet-service
          imagePullPolicy: Never
          env:
            - name: RABBITMQ_HOST
              value: host.minikube.internal
            - name: MONGO_DB_URL
              value: mongodb://bonus-booklet-service-xy123:bonus-CASE!behave7poesy@host.minikube.internal:27017/test
          ports:
            - containerPort: 3000